// Usage: npx --yes tsx tools/mcp_import.js <rc505mk2-mcp clone> [DATA dir]
// Converts the FX tables of rc505mk2-mcp (MIT, Steve Mason) into plain data
// in lib/field_map/fx.js. The reverse transforms are code; this script
// probes each one and stores the result as a lookup prefix plus an offset,
// or as a full table, so the app needs no copy of the transform code.

import fs from 'fs';
import path from 'path';
import { stats_collect } from './field_stats.js';

const probe_limit = 300;

function display_describe(reverse, observed_max) {
  if (!reverse)
    return null;
  const limit = Math.max(probe_limit, observed_max + 1);
  const out = [];
  for (let n = 0; n < limit; n++)
    out.push(String(reverse(n)));

  // Look for the shortest prefix after which display = n + offset.
  for (let prefix_len = 0; prefix_len < 64; prefix_len++) {
    const tail = out.slice(prefix_len);
    const first = Number(tail[0]);
    if (!Number.isFinite(first) || String(first) !== tail[0])
      continue;
    const offset = first - prefix_len;
    if (tail.every((s, i) => s === String(prefix_len + i + offset))) {
      const d = { prefix: out.slice(0, prefix_len) };
      if (offset)
        d.offset = offset;
      return d;
    }
  }
  return { table: out };
}

// The metadata gives display values; the forward transform maps them to
// the stored integers, so the end points give the stored range.
function range_describe(transform, meta) {
  if (!transform || !meta)
    return {};
  const shown = meta.type === 'enum'
    ? meta.values
    : [meta.range.min, meta.range.max, ...(meta.noteValues || [])];
  const raw = [];
  for (const v of shown) {
    try {
      const n = transform(String(v));
      if (Number.isInteger(n))
        raw.push(n);
    } catch {
      // A display value that the transform rejects adds no end point.
    }
  }
  if (!raw.length)
    return {};
  return { min: Math.min(...raw), max: Math.max(...raw) };
}

async function main() {
  const clone = process.argv[2];
  const data_dir = process.argv[3] || '/sandbox/colinw/ROLAND/DATA';
  if (!clone) {
    console.error('usage: npx --yes tsx tools/mcp_import.js <rc505mk2-mcp clone> [DATA dir]');
    process.exit(2);
  }
  const src = p => path.resolve(clone, 'src', p);
  const { PARAM_MAP, SEQ_TARGETS } = await import(src('params/param-map.ts'));
  const { FX_INDEX_COMMON, FX_INDEX_IFX, FX_INDEX_TFX } = await import(src('fx/fx-indexes.ts'));
  const { RC0_SEQ_FX_MAP } = await import(src('fx/fx-names.ts'));
  const { TRANSFORM_META } = await import(src('mcp/transform-meta.ts'));

  const stats = stats_collect(data_dir);
  const observed_max = (fx, tag) => {
    let max = 0;
    for (const ctx of ['ifx', 'tfx']) {
      const values = stats.get(`${ctx}/*_${fx}`)?.get(tag);
      if (values)
        max = Math.max(max, ...[...values.keys()].map(Number));
    }
    return max;
  };

  const params = {};
  for (const [fx, defs] of Object.entries(PARAM_MAP)) {
    params[fx] = Object.entries(defs)
      .map(([name, def]) => ({
        tag: def.tag,
        name,
        transform: def.transform?.name,
        ...range_describe(def.transform, TRANSFORM_META.get(def.transform)),
        display: display_describe(def.reverse, observed_max(fx, def.tag)),
      }))
      .sort((a, b) => a.tag.localeCompare(b.tag));
  }

  const types = {
    ifx: Object.fromEntries(Object.entries({ ...FX_INDEX_COMMON, ...FX_INDEX_IFX }).map(([k, v]) => [v, k])),
    tfx: Object.fromEntries(Object.entries({ ...FX_INDEX_COMMON, ...FX_INDEX_TFX }).map(([k, v]) => [v, k])),
  };

  const header = [
    '// Generated by tools/mcp_import.js from rc505mk2-mcp',
    '// (https://github.com/hysteve/rc505mk2-mcp, MIT, Copyright (c) 2026 Steve Mason).',
    '// Do not edit by hand. See THIRD_PARTY.md.',
    '',
  ].join('\n');
  const body = [
    `export const fx_types = ${JSON.stringify(types, null, 1)};`,
    `export const fx_seq_map = ${JSON.stringify(RC0_SEQ_FX_MAP, null, 1)};`,
    `export const fx_seq_targets = ${JSON.stringify(SEQ_TARGETS, null, 1)};`,
    `export const fx_params = ${JSON.stringify(params, null, 1)};`,
    '',
  ].join('\n\n');
  const out = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../lib/field_map/fx.js');
  fs.writeFileSync(out, header + body);
  console.log(`wrote ${out}: ${Object.keys(params).length} FX parameter sets`);
}

main();
